### ISSUE TITLE
Duplicate Key Input

### ISSUE THREAD

**Issue by RoloEdits** [alexpasmantier/television#1]
**Description**
It appears there is some double input from keypresses.

**Example**
![tv_double_input](https://github.com/user-attachments/assets/0f00adf7-efbe-4e94-99ea-227415f56739)

**Environment**
 - OS: Windows
 - Rust version: 1.82.0
 - Project version: 0.4.18(`0c13626d4c1b`)
 - Terminal: wezterm

**Comment by ErichDonGubler** [comment]
Fixed with <https://github.com/alexpasmantier/television/pull/3>, I hope!
