### ISSUE TITLE
Add support for folders/git ls-files channel

### ISSUE THREAD

**Issue by prabirshrestha** [alexpasmantier/television#112]
Similar to `Files` can we have `Folders` or `Directories` channel?

My use case is to create a binding in the fish shell so I can run `tv`.

Here is how my ~/.config/fish/config.fish looks like.

```fish
# Ensure tv is installed and configured
if command -q tv
    # Ctrl+Alt+f to select and paste file path
    bind \e\cf 'set -l selected_file (tv)
    if test -n "$selected_file"
        commandline -i "$selected_file"
    end
    commandline -f repaint'

    # Ctrl+Alt+d to select and paste directory path
    bind \e\cd 'set -l selected_dir (find . -type d | tv)
    if test -n "$selected_dir"
        commandline -i "$selected_dir"
    end
    commandline -f repaint'
end
```

Now in the terminal I can type `vim ` and press `ctrl+alt+f`. This will open television, I can fuzzy search and when select it will paste the pat in the terminal so it will look like `vim path/I/selceted/from/tv.txt`. I would like to do the same for directory. Right now the above code works but you can see that I'm using `find . -type d` instead. If tv has folders channel than I can directly type `tv dir` which will most likely be very fast.

It will also be good to support `git ls-files` that works with both files and directory. If I'm in a git repo, it may have lot of ignored files such as node_modules or unnecessary build folders and files which I don't care. `tv git-ls-files` and `tv-git-ls-dir`?

**Comment by alexpasmantier** [comment]
@prabirshrestha Sure thing for directories.

For `git ls-files` and dirs, using a custom channel and being able to invoke that custom channel from the command line (not yet implemented but probably straightforward enough) could be a quick alternative if you need to iterate quickly on this.

**Comment by prabirshrestha** [comment]
Can cables be used without the toml file? the reason for this I want to do it all in vim script without asking the consumers to update the toml files.

```bash
tv cable --source-command="git ls-files" --preview-command="bath -n --color=always {0}"
```

**Comment by alexpasmantier** [comment]
You could do something like 
```bash
git ls-files | tv --preview 'bat -n --color=always {}'
```
which should give you what you want:

<img width="2990" alt="Screenshot 2024-12-12 at 11 23 46" src="https://github.com/user-attachments/assets/052fffce-8980-4d5c-8fd8-477267856668" />

**Comment by alexpasmantier** [comment]
I believe this was fixed by custom channels and https://github.com/alexpasmantier/television/pull/130.

Closing for now
