### ISSUE TITLE
color themes not applied

### ISSUE THREAD

**Issue by zachvalenta** [alexpasmantier/television#117]
I've updated the theme in my config but don't see it reflected when I open `television`:

<img width="1920" alt="Screenshot 2024-12-13 at 4 35 53 PM" src="https://github.com/user-attachments/assets/23512283-ead3-4293-a835-f4f12cec7f2a" />

Just to sanity check, I enabled icons and those are reflected:

<img width="1920" alt="Screenshot 2024-12-13 at 4 36 29 PM" src="https://github.com/user-attachments/assets/84305c9e-06c6-4f6f-a677-ce740cd95619" />

Another sanity check is that the config symlink reflects the updates in my version-controlled dotfile, so it doesn't look like any funny business there:

<img width="610" alt="Screenshot 2024-12-13 at 4 45 23 PM" src="https://github.com/user-attachments/assets/d5b81a99-55be-4fbd-832a-0033c7cfbbc2" />

I installed `television` earlier today on my work machine [where all this is happening] and thought maybe I installed it right before [the PR](https://github.com/alexpasmantier/television/pull/114) to add color themes was merged, just to be sure I force updated:
```sh
$ cargo install --locked --force television
```

Also, some OS details in case they're relevant:

```sh
neofetch
                    'c.          zvalenta@Zachs-MacBook-Air.local
                 ,xNMM.          --------------------------------
               .OMMMMo           OS: macOS 14.6.1 23G93 arm64
               OMMM0,            Host: MacBookAir10,1
     .;loddo:' loolloddol;.      Kernel: 23.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 28 days, 6 hours, 4 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 156 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: FiraMonoNerdFontComplete-Regular 12
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1
       .cooc,.    .,coo:.        Memory: 2512MiB / 16384MiB

```

**Comment by alexpasmantier** [comment]
@zachvalenta in order to try out new features in between releases you'd have to clone the repo and build from source.

Installing via cargo will always give you the latest release version which in this case is 0.6.2.

You can confirm that with:
```
tv --version
```

**Comment by zachvalenta** [comment]
Sorry about that! For some reason I saw that merge and thought "new release" but didn't actually verify that was true 🫠

**Comment by sunjam** [comment]
Ran into same problem on $ ~/tv --version
television 0.9.4
target triple: aarch64-unknown-linux-gnu
build: 1.84.0 (2025-01-20
