### ISSUE TITLE
stdout is not consistent

### ISSUE THREAD

**Issue by prabirshrestha** [alexpasmantier/television#118]
**Description**
`tv` stdout is not consistent due to new lines not getting handled correctly.

**Example**
A [minimal reproducible code example](https://stackoverflow.com/help/minimal-reproducible-example) where the bug happens.

![image](https://github.com/user-attachments/assets/6123baf8-0970-4345-a91d-cd25b19ca9dd)

**Expected behavior**

`git ls-files | tv` returns an empty new line.

**Actual behavior**

`git ls-files | tv` shouldn't return an empty new line. This should behave similar to `fzf` and just `tv`.

**Environment**
 - OS: Mac
 - Rust version: 1.83.0
 - Project version: 0.6.2
 - [Any other dependency version if needed]

**Additional context**

I'm working on [tv.vim](https://github.com/prabirshrestha/tv.vim) vim plugin and I need to care about the stdout. Currently the plugin works for files as `tv` is returning only one line but `git ls-files | tv` returns two lines so my parsing logic doesn't work correctly. While I can update my plugin to handle this edge case I think it should be fixed in tv cli so other tools using tv don't have to have special hacks around this.

**Comment by alexpasmantier** [comment]
Thanks for the feedback 🙏🏻 

Fixed by #121
