### ISSUE TITLE
ctrl+j, ctrl+k should be move up and down the selection

### ISSUE THREAD

**Issue by prabirshrestha** [alexpasmantier/television#135]
It is common for vim users to use ctrl+j and ctrl+k to move up and down. FZF uses this by default. would be good if this was also set by default.

is it possible to set multiple keybindings for the same movement? if not it would be good to add support to as sometimes based on the circumstances I use up and down arrow with ctrl+j and ctrl+k.

**Comment by AyaanAhmed25** [comment]
ctrl+n and ctrl+p will also be appreciated. fzf does both out of the box.

**Comment by yavorski** [comment]
`ctrl+w` and `ctrl-backspace` to delete a word would be nice as well
