### ISSUE TITLE
Allow hiding the preview title

### ISSUE THREAD

**Issue by baldwindavid** [alexpasmantier/television#147]
**Problem**
Previous to #144 placing the input bar at the top resulted in the preview title surprisingly flipping to the bottom. That PR will improve that situation, but I'd prefer to completely hide the preview title in its current state.

Perhaps there is a type of channel where it would be necessary, but for all the builtin channels, it is redundant information already displayed in the results pane and takes up screen real estate.

**Feature**
A configuration option to hide the preview title. I suppose this could be `preview_title_position = "none"` or `display_preview_title = true | false`.

**Additional context**

Rather than hiding I do wonder if an alternative option might improve that title's usefulness. It's currently its own distinct element separate of the preview panel and is not consistent with the other panels in that it has no "label" (e.g. Pattern, Results, Preview). Thus, I wonder if it's content could actually take the place of the word "Preview" above the preview panel. So if the filename of the current selection is `app.js` then that text would appear as the label above the preview rather than the text "Preview".

**Comment by alexpasmantier** [comment]
Thanks for the feedback.

> Rather than hiding I do wonder if an alternative option might improve that title's usefulness. It's currently its own distinct element separate of the preview panel and is not consistent with the other panels in that it has no "label" (e.g. Pattern, Results, Preview). Thus, I wonder if it's content could actually take the place of the word "Preview" above the preview panel. So if the filename of the current selection is app.js then that text would appear as the label above the preview rather than the text "Preview".

This is indeed a good idea, implemented in #148

**Comment by alexpasmantier** [comment]
<img width="2552" alt="Screenshot 2024-12-28 at 15 18 42" src="https://github.com/user-attachments/assets/08e440c2-6878-4a0f-8734-83a8e8b84e5a" />

**Comment by baldwindavid** [comment]
Awesome, love it! I also like the removal of the "Input" label as it didn't seem necessary.
