### ISSUE TITLE
Prefill input text

### ISSUE THREAD

**Issue by baldwindavid** [alexpasmantier/television#152]
**Problem**
I'd like to be able to prefill the "input" text when initiating television as if it had been typed in with results pre-filtered based upon that input. I still want to be able to change/delete the characters in the input. Perhaps it's already able to do so, but it's not obvious to me.

The way I use television is from within an editor (https://zed.dev/) with a keybinding that effectively runs `zed "$(tv text)"` to open a terminal within the editor, search text, and then open a selection within the editor.

This all works, but ideally I could prefill the search with the current selection if there is one. Zed has a way to get access to this value as `$ZED_SELECTED_TEXT`.

**Feature**
I'm imagining some sort of option to provide the prefilled input such as `tv text --input <STRING>`. I could then run `zed "$(tv text --input $ZED_SELECTED_TEXT)"` to integrate within the editor.

**Comment by alexpasmantier** [comment]
Seems legit and pretty straightforward to implement 👍🏻 

I'm really interested in people sharing their workflow ideas through the wiki, if you'd mind showing your zed integration (could be a small video sample or screenshots) that would be awesome and greatly appreciated!

**Comment by baldwindavid** [comment]
Oh, nice. That was quick, ha.
I'm curious; is there an easy way to install `main` to test without a release? I can install either via brew or cargo. Perhaps a little tweak to these instructions?...

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update
cargo install --locked television
```

**Comment by alexpasmantier** [comment]
The easiest way would be to just clone the repo and build using cargo:
```sh
git clone git@github.com:alexpasmantier/television.git
cd television
cargo build --release
```

You could then alias `tv` to `$CLONING_DIR/television/target/release/tv` or just run it from there:
```sh
alias tv=$CLONING_DIR/television/target/release/tv
tv files

# OR

$CLONING_DIR/television/target/release/tv files
```

**Comment by baldwindavid** [comment]
👍 , thanks. Was just eyeing the Makefile and figured that might be the ticket.

**Comment by baldwindavid** [comment]
> I'm really interested in people sharing their workflow ideas through the wiki, if you'd mind showing your zed integration (could be a small video sample or screenshots in [this newly created section](https://github.com/alexpasmantier/television/wiki/Showcase)) that would be awesome and greatly appreciated!

Okay, @alexpasmantier , added the first showcase item. Feel free to edit/delete as you see fit for that page as it's mostly just pulled from a recent post in the Zed repo... https://github.com/zed-industries/zed/discussions/22581

**Comment by alexpasmantier** [comment]
That looks perfect!

Good job on the integration too, looks sweet!
