### ISSUE TITLE
Support updating preview theme via symlink

### ISSUE THREAD

**Issue by baldwindavid** [alexpasmantier/television#169]
**Problem**
I switch all of my cli tooling between light and dark modes via a very boring method of changing symlinks to "adaptive" theme files between dark and light source files.

For example, this works for switching the television UI theme...

**config.toml**
```toml
[ui]
theme = "adaptive"
```

**toggle theme script**
```sh
...
# switch to dark UI theme
ln -s -f ~/.config/television/themes/catppuccin.toml ~/.config/television/themes/adaptive.toml;
...
```

However, this does not seem to work for the preview theme...

```toml
[previewers.file]
theme = "adaptive"
```

Since television is leveraging bat themes and I'm already toggling a similar "adaptive" theme for bat for other tools I thought this might _just work_...

**toggle theme script (continued)**
```sh
# switch to dark bat theme
ln -s -f ~/.config/bat/themes/CatppuccinMocha.tmTheme ~/.config/bat/themes/adaptive.tmTheme;
```

Alas, it does not. I suspect that the reference to the `previewers.file.theme` is to perhaps a cached bat theme rather than directly to the theme file. Maybe that is the way it should be, 🤷 .

I would note that in that theme switching script I'm also setting the `BAT_THEME`...

**toggle theme script (continued)**
```sh
export BAT_THEME="CatppuccinMocha"
```

I do wonder if `BAT_THEME` might be a good default in the case that no syntax theme has been set at all similar to other tools so it works out of the box for those setting that variable.

Similarly, although I'm not running into a problem with the UI theme and I think it would require some mapping, it might be nice if the UI theme defaulted colors to `LS_COLORS` similar to other tools. I happen to toggle that one as well...

**toggle theme script (continued)**
```sh
export LS_COLORS="$(vivid generate catppuccin-mocha)"
```

That way it mostly works out of the box and if someone has strong opinions about it they are welcome to create a custom theme.

**Comment by baldwindavid** [comment]
It probably goes without saying that I _can_ brute force hardcoded theme names by toggling the symlink for the entire `.config/television/config.toml` file, but then there are two separate config files with duplicate config other than the theme keys. I'd like to avoid that, but that's my current workaround.

**Comment by alexpasmantier** [comment]
I think relying on BAT_THEME is indeed a good default if it's set to determine the syntax highlighting colorscheme to use (and it would solve your problem in a quite simple way).

> Alas, it does not. I suspect that the reference to the previewers.file.theme is to perhaps a cached bat theme rather than directly to the theme file. Maybe that is the way it should be, 🤷 .

Correct


LS_COLORS would also be nice indeed although I'm not going to prioritize it for the moment in favor of more functional changes.

If anyone is willing to try out a PR, go for it 😊

**Comment by baldwindavid** [comment]
Cool, guess I was thinking that a television configured theme would take precedent and fallback to `BAT_THEME`.

Regardless, I made the mistake of thinking this would work for my use case and it actually doesn't. When I run the shell script to toggle the theme the `BAT_THEME` env variable is updated in the current shell. That means it works for subsequent shells. However, I typically toggle the theme directly from a running editor and that automatically updates the theme for Zed, Helix, Mac OS, etc.

I thought a new workaround of building the cache right after changing the theme file might work, but doesn't seem to...

```bash
ln -s -f ~/.config/bat/themes/CatppuccinMocha.tmTheme ~/.config/bat/themes/adaptive.tmTheme;
bat cache --build
```

Oh well. I have a workaround and perhaps others will have different ideas of supporting theme switching in the future. Thanks for the change.

**Comment by baldwindavid** [comment]
Cool, guess I was thinking that a television configured theme would take precedent and fallback to `BAT_THEME`.

Regardless, I made the mistake of thinking this would work for my use case and it actually doesn't. When I run the shell script to toggle the theme the `BAT_THEME` env variable is updated in the current shell. That means it works for subsequent shells. However, I typically toggle the theme directly from a running editor and that automatically updates the theme for Zed, Helix, Mac OS, etc.

**But...I have a workaround that would have worked in the first place.**

Here I'm building the cache right after changing the theme file...

```bash
ln -s -f ~/.config/bat/themes/CatppuccinMocha.tmTheme ~/.config/bat/themes/adaptive.tmTheme;
bat cache --build
```

...and configuring this theme in `config.toml`...

```toml
[previewers.file]
theme = "adaptive"
```

This effectively results in the same thing as changing out the file with just the need to rebuild the cache. Thanks for the change anyway as that seems like a good thing to support.
