### ISSUE TITLE
`ctrl-w` not updating the list items

### ISSUE THREAD

**Issue by yavorski** [alexpasmantier/television#170]
**Description**
When deleting a word with `ctrl-w` list results are not updated until you start typing again.

**Example**
Type some words in the prompt (input_bar) and then start to delete them with `ctrl-w`.

**Expected behavior**
When a word is deleted with `ctrl-w` the search results entries should be updated with the new query in mind.

**Actual behavior**
Not updating the list items entries.

**Environment**
 - OS: linux
 - Project version: v0.8.0

**Comment by alexpasmantier** [comment]
Indeed, thanks for the feedback 🙏
