### ISSUE TITLE
Support Shell Integration For Fish

### ISSUE THREAD

**Issue by Ktoks** [alexpasmantier/television#182]
**Problem**
I would like to propose fish shell integration be supported.

**Feature**
Ctrl-r, etc. . . features be supported - similarly to fzf.

**Examples**
Ctrl-r - allows the user to search past command uses in $HOME/fish/fish_history

**Additional context**
I don't know that there is additional context needed.

**Comment by alexpasmantier** [comment]
Hi, thanks for the feedback, much appreciated.

I added a minimal implementation for fish in https://github.com/alexpasmantier/television/pull/186.
