### ISSUE TITLE
Consider Fat LTO instead of Thin LTO for the project

### ISSUE THREAD

**Issue by zamazan4ik** [alexpasmantier/television#185]
**Problem**
It's not a problem - it's an improvement idea for the project.

**Feature**
I decided to experiment with more optimized LTO versions for the project and switched from Thin LTO to Fat LTO plus experimented with `codegen-units = 1` option. I have made quick tests (Fedora 41, Rust 1.82, the latest version of the project) - here are the results for the `tv` binary:

* Release + `codegen-units = 1`: 11 Mib
* Release + Thin LTO (current default): 14 Mib
* Release + Fat LTO: 11 Mib
* Release + `codegen-units = 1` + Fat LTO: 9.7 Mib
* Release + `codegen-units = 1` + Thin LTO: 11 Mib

I think it could be worth to switch to Fat LTO and/or enable `codegen-units = 1`.

**Examples**
N/A

**Additional context**
N/A

**Comment by alexpasmantier** [comment]
Thanks for the feedback, opened a PR 🙏🏻
