### ISSUE TITLE
TV doesn't seem to respect `TELEVISION_CONFIG` env variable on windows

### ISSUE THREAD

**Issue by JustBarnt** [alexpasmantier/television#20]
**Description**
TV is not respecting me setting the `env` varialbe `TELEVISION_CONFIG`. On Windows. I have tried setting it the the Environment Variable UI that windows provides, as well as setting it in my Nushell env file which is the my default shell.

**Example**
1. Install Television via cargo
```bash
cargo install television
```
2. Set the Environment Variable either through the terminal in your shell profile or through the Windows GUI that is available.
3. Change something in your `config.toml` file to easily recognize if it has found the config.
   I changed my up and down keymaps from `<C-n>` and `<C-p>` to `<C-j>` and `<C-k>`
4. Run tv with any channel and try to use something that you changed from your config, such as new keymaps.

**Expected behavior**
Television properly finds the config path on Windows, when an environment variable is set.

**Actual behavior**
Television does not find the config path via the environment variable, it is still using the default values.

**Environment**
 - OS Name: Microsoft Windows 11 Pro
 - OS Version: 10.0.22631 N/A Build 22631
 - Rust version: rustc 1.80.1 (3f5fd8dd4 2024-08-06)
 - Project version:
   television 0.4.20
   target triple: x86_64-pc-windows-msvc
   build: 1.80.1 (2024-11-13)
 - Terminal: 
   Wezterm: wezterm 20240812-215703-30345b36

**Additional context**
When calling `tv --version` it prints out the config directory as

```bash
Config directory: C:\Users\bwilliams\AppData\Local\alexpasmantier\television\config
```

I think there may be an issue with the default directory created as well since it creates a `dir` for your user name instead of just "television" which the readme says it should be `<username>\AppData\Local\television`

**Comment by JustBarnt** [comment]
Update: I tried moving my config.toml file into the defaulted directory when running `tv --version` and it still doesn't read the config file

**Comment by alexpasmantier** [comment]
Thanks for the feedback 🙏🏻

**Comment by JustBarnt** [comment]
@alexpasmantier you're welcome! And thank you for this awesome utility!
