### ISSUE TITLE
Provide a .deb package

### ISSUE THREAD

**Issue by sbstn87** [alexpasmantier/television#27]
Hi,

can you perhaps provide a .deb package for an easy installation on Debian based distros?

This would also enable television to be added to deb-get:
https://github.com/wimpysworld/deb-get

**Comment by alexpasmantier** [comment]
Hi, thanks for the suggestion.

I added a deb package release step to the CD pipeline.

You may find a `.deb` package for the latest release [here](https://github.com/alexpasmantier/television/releases/tag/0.4.22).
