### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by sga-13** [alexpasmantier/television#28]
Greetings,

I made an AUR package - can you please check it [television-bin](https://aur.archlinux.org/packages/television-bin). I have installed tv by this and it works well. If it seems fine, maybe you can add it in readme.

Thank you.

**Comment by alexpasmantier** [comment]
Hi, thanks for showing interest in the project.

I think this should be added as a CD workflow to be done automatically with each release.

Also I changed version tags from `vx.y.z` to `x.y.z` in recent releases which means your `PKGBUILD` will need a couple of changes for these.

Are you willing to start a PR for that?

**Comment by sga-13** [comment]
yes, i well try to get both done, i have a bit of a busy week on hand, so it might be delayed a bit

**Comment by sga-13** [comment]
television is now an official arch package, so aur '-bin' package is not required anymore, so i am closing this.
