### ISSUE TITLE
Input is not being preserved

### ISSUE THREAD

**Issue by sga-13** [alexpasmantier/television#29]
**Description**
I have a script where i have some input given to fzf/tv by std in, there are some terms which are tab separated and some by space (and all most all possible input things). If i use fzf for selection, the output generated preserves the tabs and spaces, whereas tv is possibly converting tabs to spaces.

here is a video of expected behavior (fzf) and issue in tv. Commands are essentially simple cut commands, splitting by tab separator. 

![output](https://github.com/user-attachments/assets/f9354e73-ba13-4676-837f-379cd4fc116a)

**Example**
(sorry this is not a minimal example, but the quickest one i can come up with which is elaborate) https://codeberg.org/sga/pages/src/branch/main/scripts/launcher.sh

**Expected behavior**
preserving input characters.

**Actual behavior**
characters are not prsereved.

**Environment**
 - OS: Linux 6.11.8-arch1-2
 - Rust version: rustc 1.82.0 (f6e511eec 2024-10-15) (Arch Linux rust 1:1.82.0-2)
 - Project version:
 television 0.4.21
target triple: x86_64-unknown-linux-gnu
build: 1.82.0 (2024-11-13)
 - [Any other dependency version if needed]

**Comment by alexpasmantier** [comment]
Thanks for the feedback 🙏🏻 
Should be fixed by #62
