### ISSUE TITLE
TV is not using the available screen space

### ISSUE THREAD

**Issue by xircon** [alexpasmantier/television#36]
**Problem**
As per titile:
![image](https://github.com/user-attachments/assets/2220b9e1-f501-41d9-b341-07fb3d340b06)

EndeavourOS, kitty - Hack 16pt (I'm old :smile: )
**Feature**
Decrease the borders

**Comment by gcanat** [comment]
Read the docs more carefully: https://github.com/alexpasmantier/television?tab=readme-ov-file#customization
You can edit `config.toml` and add:
```toml
[ui]
ui_scale = 100
```

**Comment by uncenter** [comment]
I think as evidenced by OP, and my own confusion/frustration, perhaps it would make sense to change the default UI scale to a normal `100`? I've never seen a CLI/TUI app constrict itself to a default of 80% of available space before, and on my terminal with my viewing size even the help text about the keybinds is partially cut off. It feels a little janky, and like the user has something wrong about their setup, when it is really just a poor default.

**Comment by alexpasmantier** [comment]
Indeed, that makes sense. Will issue a PR for that asap 👍

Thanks for the feedback.

**Comment by alexpasmantier** [comment]
Done in #47

**Comment by uncenter** [comment]
Thank you!
