### ISSUE TITLE
create home-brew tap for MacOS

### ISSUE THREAD

**Issue by prabirshrestha** [alexpasmantier/television#37]
Create homebrew tap for MacOS. https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Example:
* https://github.com/Homebrew/homebrew-core/pull/157934

**Comment by alexpasmantier** [comment]
https://github.com/alexpasmantier/homebrew-television

Television should now be installable using:
```sh
brew install alexpasmantier/television/television
```

I'm not sure I'm able to produce bottles for every macOS version directly from my machine though. Will have to check that later.

**Comment by joshmedeski** [comment]
Got this error when trying to install the brew tap:
```
curl: (56) The requested URL returned error: 404

Error: television: Failed to download resource "television"
Download failed: https://ghcr.io/v2/homebrew/core/television/blobs/sha256:a72c29f504a8fa91eedaeef12af0ee3c5afdbe72efb3150cf759ecde740b25f3
```

**Comment by alexpasmantier** [comment]
Hi, thanks for the feedback.

Do you still get that same error if you manually add the tap first?

```
brew tap alexpasmantier/television
```

**Comment by alexpasmantier** [comment]
Ideally, it would be nice to add television to [homebrew-core](https://github.com/Homebrew/homebrew-core), which would really simplify the installation on macos and make it quite faster since homebrew automatically produces bottles (pre-built binaries for every recent macOS version) for you.
```sh
brew install television
```

If someone is willing to try that out and file a PR on [homebrew-core](https://github.com/Homebrew/homebrew-core), I'd be extremely grateful 🙏🏻

**Comment by joshmedeski** [comment]
Yes same problem, I recommend shipping a new release and I can retry.

**Comment by alexpasmantier** [comment]
@joshmedeski Are you still having that issue when trying to install using homebrew?

**Comment by joshmedeski** [comment]
It works now, thanks!

**Comment by chenrui333** [comment]
FYI, there is an open PR to include the project into homebrew-core, https://github.com/Homebrew/homebrew-core/pull/198998

**Comment by alexpasmantier** [comment]
@chenrui333 Great! Does the process require any intervention on my part?

**Comment by p-linnane** [comment]
@alexpasmantier The PR is approved and currently merging. Users should be able to run `brew install television` in about 30 minutes. Would you like help migrating your tap to point to Homebrew/core? It'll allow your existing users to continue to receive updates with no disruption.

**Comment by alexpasmantier** [comment]
@p-linnane Thanks so much for opening that PR; it's greatly appreciated.

Given that television isn't widely used at the moment, wouldn’t it make sense to take this opportunity to drop the custom tap altogether and avoid maintaining two sources? Or, if we simply make it point to Homebrew core, would that eliminate any additional maintenance on the custom tap?

**Comment by alexpasmantier** [comment]
Perfect.

Yes, if you're able to do so that would greatly help in doing things the right way regarding Homebrew. Thanks!

**Comment by p-linnane** [comment]
https://github.com/alexpasmantier/homebrew-television/pull/1

**Comment by alexpasmantier** [comment]
Merged! Thanks for the help 🙏🏻
