### ISSUE TITLE
Register custom actions via the cli

### ISSUE THREAD

**Issue by prabirshrestha** [alexpasmantier/television#38]
I would like to build a vim plugin for television and would like to know if you can support custom actions.

This allows to implement having custom binding sent from vim and when those keys are pressed television cli would return the key pressed along with the item that was selected. 

```bash
tv --action=ctrl-t,ctrl-v,ctrl-x
```

When `ctrl-t` is pressed it should write the following.

```
ctrl-t
/path/to/selected/item
```

This allows me to read the first line and know what action was preformed.

This allows me to implement `ctrl-t` for open in new tab, `ctrl-v` to open in new vertical split, `ctrl-x` for open in new horizontal split. One can also customize this in the vim script if needed.

Example: https://github.com/mattn/vim-fz/pull/13

**Comment by alexpasmantier** [comment]
That sounds feasible enough.

Will look into that ASAP and come up with a PR.

**Comment by alexpasmantier** [comment]
You may now pass custom keybindings which you wish to pass through upon exiting television:
```sh
tv --passthrough_keybindings=ctrl-t,ctrl-v,ctrl-x files
```
will output, when triggering `ctrl-v` for instance:
```
ctrl-v
my_selected_entry
```
