### ISSUE TITLE
Mention that `XDG_CONFIG_HOME` is respected on all platforms for configuration directory

### ISSUE THREAD

**Issue by uncenter** [alexpasmantier/television#46]
The README currently reads as if the program does not respect the `XDG_CONFIG_HOME` variable, and instead uses the operating system specification for macOS and Windows. Where, in reality, the code appears to always check `XDG_CONFIG_HOME` first before defaulting to whatever else.

**Comment by alexpasmantier** [comment]
You're right. Thanks for the feedback. Will add that to the docs 🫡
