### ISSUE TITLE
Git branches channel

### ISSUE THREAD

**Issue by sd2k** [alexpasmantier/television#8]
Cool project! I thought of a potential new feature: git branches.

**Problem**
I have no good way of listing and previewing git branches right now.

**Feature**
A built in channel for git branches would be cool. I imagine the preview could show either the git log as a nice tree, or the git diff with HEAD.

**Examples**
N/A

**Additional context**
[This blog post](https://www.thevaluable.dev/fzf-git-integration/#working-with-branches) has a section on building something like this with fzf.

**Comment by alexpasmantier** [comment]
I'm currently working on a feature that will cover this.

Closing the issue for now.
