### ISSUE TITLE
Customizing the color theme

### ISSUE THREAD

**Issue by moritzwilksch** [alexpasmantier/television#80]
**Problem**
The television interface appears in a somewhat illegible dark blue in my terminal (`iTerm` on MacOS, `TERM=xterm-256color`) setup. Is there any way to change that and customize the overall theme, not just the preview?

<img width="778" alt="image" src="https://github.com/user-attachments/assets/f87b5c27-da4b-48e8-b56d-95ee832147e4">

**Feature**
It would be great to be able to customize the theme similar to how I can customize the preview theme in the `config.toml`

**Examples**
The readme contains a screenshot with a nice theme, although that's probably a global terminal color theme.

**Additional context**
Moreover, when using `television` in `tmux`, the searchbox is filled with a weird red for some reason:

<img width="842" alt="image" src="https://github.com/user-attachments/assets/ba5e909b-6534-4fa0-8cf8-f921bf2357f1">

tmux env: `TERM=screen-256color`

**Comment by zachvalenta** [comment]
First off:

* found you through the latest batch from [Terminal Trove](https://terminaltrove.com/new/)
* great job with this! huge fan of Telescope, glad to see it reimagined outside of Neovim (fond as I am of Neovim)

Argument for fixing color now:

Some|many|most users [of the type who would find this project] are configuring colors per tool i.e. I have one theme for my prompt, another theme for ls, and so on i.e. "Fix it by changing your terminal theme" means changing other things as well and probably outright losing the UI you already have just to even read the output of `television`

```sh
# prompt
eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/multiverse-neon.omp.json)"
# ls
export LS_COLORS="$(vivid generate catppuccin-mocha)"
```

The other thing is that [terminal colors as an entire topic is a tricky](https://jvns.ca/blog/2024/10/01/terminal-colours/). "Fiddle with your terminal and then the tool will be usable" will mean, I think, that no one uses the tool until it is usable.

Again, great job with this and look forward to seeing it develop.

**Comment by ristomatti** [comment]
This tool looks fantastic indeed! I have to say I agree with @zachvalenta. I've used my current terminal color theme for several years and would prefer not to touch them at this point. Please consider making at least the borders and search text color. :pray:

![image](https://github.com/user-attachments/assets/792e0dca-6853-419f-9c4f-3b48a9e1ffef)

:see_no_evil:

**Comment by alexpasmantier** [comment]
Thanks for the feedback.

We're currently working our way towards having global colorschemes.

Cheers

**Comment by fooness** [comment]
> **Additional context** Moreover, when using `television` in `tmux`, the searchbox is filled with a weird red for some reason:
> <img alt="image" width="842" src="https://private-user-images.githubusercontent.com/58488209/390335458-ba5e909b-6534-4fa0-8cf8-f921bf2357f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzY1NjEsIm5iZiI6MTczMzkzNjI2MSwicGF0aCI6Ii81ODQ4ODIwOS8zOTAzMzU0NTgtYmE1ZTkwOWItNjUzNC00ZmEwLThjZjgtZjkyMWJmMjM1N2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE2NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4M2U4ZGI0MWYzZjA4ODUxM2QyZGM0Y2JkMjFmNzNlOGM1NjJlNmM1Mjk5OWQ2NzU5MDNiMGY1YTdiOGYwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VRckTRvn-i2tPSQ40Y7dJARc7PvdllNJgHYz5H-F1B4">
> 
> tmux env: `TERM=screen-256color`

@moritzwilksch Not sure if you’re already aware of this; I just figured this out very recently: using tmux env `TERM=tmux` or `TERM=tmux-256color` — or via tmux command or config option `set -g default-terminal "tmux"` / `set -g default-terminal "tmux-256-color"` — the input/prompt line looks correct in tmux.

via: https://github.com/tmux/tmux/wiki/FAQ#i-dont-see-italics-or-italics-and-reverse-are-the-wrong-way-round
